import type {
  AppState,
  Branch,
  Certificate,
  Competency,
  Course,
  CourseModule,
  DailyTraining,
  EmployeeAssignment,
  EmployeeCompetency,
  EmployeeProfile,
  ExamAttempt,
  LearningPath,
  LearningPathCourse,
  Lesson,
  LessonContent,
  LessonProgress,
  Notification,
  Organization,
  PracticalAssessment,
  PricingFormulaConfig,
  QuizOption,
  QuizQuestion,
  ScenarioStep,
  Sop,
  SopAcknowledgment,
  SopVersion,
  TrainingRecommendation,
  TrainingScenario,
  User,
} from "./types";

const ORG_ID = "org_arya";
const BRANCH_CENTRAL = "branch_central";
const BRANCH_SECOND = "branch_second";

const NOW = "2025-09-20T08:00:00.000Z";
const WEEK_AGO = "2025-09-13T08:00:00.000Z";
const MONTH_AGO = "2025-08-20T08:00:00.000Z";

export const organization: Organization = {
  id: ORG_ID,
  name: "گالری طلای آریا",
  nameEn: "Arya Gold Gallery",
  createdAt: "2023-03-15T10:00:00.000Z",
  settings: {
    defaultPassingScore: 70,
    passingScore: 70,
    requireSopAcknowledgment: true,
    allowSelfEnrollment: false,
    goldPurityStandard: 750,
    pricingFormulaId: "price_cfg_1",
  },
};

export const branches: Branch[] = [
  {
    id: BRANCH_CENTRAL,
    organizationId: ORG_ID,
    name: "شعبه مرکزی",
    address: "تهران، خیابان ولیعصر، بالاتر از پارک وی، پلاک ۱۴۲۸",
    city: "تهران",
    phone: "021-22014567",
    isActive: true,
  },
  {
    id: BRANCH_SECOND,
    organizationId: ORG_ID,
    name: "شعبه دوم",
    address: "تهران، بازار بزرگ، راسته زرگرها، سرای امید، طبقه همکف، پلاک ۲۷",
    city: "تهران",
    phone: "021-55667890",
    isActive: true,
  },
];

export const users: User[] = [
  {
    id: "user_owner",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "owner@arya-gold.ir",
    phone: "09121234567",
    fullName: "مهرداد آریایی",
    role: "owner",
    systemRole: "owner",
    avatarInitials: "مآ",
    isActive: true,
    createdAt: "2023-03-15T10:00:00.000Z",
    lastLoginAt: NOW,
  },
  {
    id: "user_mgr_central",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "manager.central@arya-gold.ir",
    phone: "09123334455",
    fullName: "سارا موسوی",
    role: "manager",
    systemRole: "manager",
    avatarInitials: "سم",
    isActive: true,
    createdAt: "2023-04-01T09:00:00.000Z",
    lastLoginAt: NOW,
  },
  {
    id: "user_mgr_second",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    email: "manager.second@arya-gold.ir",
    phone: "09124445566",
    fullName: "رضا کریمی",
    role: "manager",
    systemRole: "manager",
    avatarInitials: "رک",
    isActive: true,
    createdAt: "2023-05-10T09:00:00.000Z",
    lastLoginAt: WEEK_AGO,
  },
  {
    id: "user_trainer",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "trainer@arya-gold.ir",
    phone: "09125556677",
    fullName: "نیلوفر احمدی",
    role: "trainer",
    systemRole: "trainer",
    avatarInitials: "نا",
    isActive: true,
    createdAt: "2023-06-01T09:00:00.000Z",
    lastLoginAt: NOW,
  },
  {
    id: "user_emp_nima",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "nima.salehi@arya-gold.ir",
    phone: "09126667788",
    fullName: "نیما صالحی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "نص",
    isActive: true,
    createdAt: "2024-01-15T09:00:00.000Z",
    lastLoginAt: NOW,
  },
  {
    id: "user_emp_zahra",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "zahra.hosseini@arya-gold.ir",
    phone: "09127778899",
    fullName: "زهرا حسینی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "زح",
    isActive: true,
    createdAt: "2024-02-20T09:00:00.000Z",
    lastLoginAt: WEEK_AGO,
  },
  {
    id: "user_emp_ali",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "ali.rezaei@arya-gold.ir",
    phone: "09128889900",
    fullName: "علی رضایی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "عر",
    isActive: true,
    createdAt: "2024-03-10T09:00:00.000Z",
    lastLoginAt: NOW,
  },
  {
    id: "user_emp_maryam",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    email: "maryam.kazemi@arya-gold.ir",
    phone: "09129990011",
    fullName: "مریم کاظمی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "مک",
    isActive: true,
    createdAt: "2024-04-05T09:00:00.000Z",
    lastLoginAt: WEEK_AGO,
  },
  {
    id: "user_emp_hossein",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    email: "hossein.najafi@arya-gold.ir",
    phone: "09121112233",
    fullName: "حسین نجفی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "حن",
    isActive: true,
    createdAt: "2024-05-12T09:00:00.000Z",
    lastLoginAt: MONTH_AGO,
  },
  {
    id: "user_emp_fatemeh",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "fatemeh.moradi@arya-gold.ir",
    phone: "09122223344",
    fullName: "فاطمه مرادی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "فم",
    isActive: true,
    createdAt: "2024-06-01T09:00:00.000Z",
    lastLoginAt: NOW,
  },
  {
    id: "user_emp_amir",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    email: "amir.bagheri@arya-gold.ir",
    phone: "09123334400",
    fullName: "امیر باقری",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "اب",
    isActive: true,
    createdAt: "2024-07-18T09:00:00.000Z",
    lastLoginAt: WEEK_AGO,
  },
  {
    id: "user_emp_leila",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    email: "leila.jamshidi@arya-gold.ir",
    phone: "09124445500",
    fullName: "لیلا جمشیدی",
    role: "employee",
    systemRole: "employee",
    avatarInitials: "لج",
    isActive: true,
    createdAt: "2025-01-08T09:00:00.000Z",
    lastLoginAt: NOW,
  },
];

export const employeeProfiles: EmployeeProfile[] = [
  {
    id: "ep_nima",
    userId: "user_emp_nima",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    jobRole: "sales_associate",
    hireDate: "2024-01-15",
    knowledgeLevel: 0,
    practicalStatus: "competent",
    workAuthorization: "independent",
    supervisorId: "user_mgr_central",
    streakDays: 0,
  },
  {
    id: "ep_zahra",
    userId: "user_emp_zahra",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    jobRole: "cashier",
    hireDate: "2024-02-20",
    knowledgeLevel: 0,
    practicalStatus: "competent",
    workAuthorization: "independent",
    supervisorId: "user_mgr_central",
  },
  {
    id: "ep_ali",
    userId: "user_emp_ali",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    jobRole: "inventory",
    hireDate: "2024-03-10",
    knowledgeLevel: 0,
    practicalStatus: "supervised",
    workAuthorization: "supervised_only",
    supervisorId: "user_mgr_central",
  },
  {
    id: "ep_maryam",
    userId: "user_emp_maryam",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    jobRole: "sales_associate",
    hireDate: "2024-04-05",
    knowledgeLevel: 0,
    practicalStatus: "supervised",
    workAuthorization: "supervised_only",
    supervisorId: "user_mgr_second",
  },
  {
    id: "ep_hossein",
    userId: "user_emp_hossein",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    jobRole: "repair_intake",
    hireDate: "2024-05-12",
    knowledgeLevel: 0,
    practicalStatus: "competent",
    workAuthorization: "independent",
    supervisorId: "user_mgr_second",
  },
  {
    id: "ep_fatemeh",
    userId: "user_emp_fatemeh",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    jobRole: "customer_service",
    hireDate: "2024-06-01",
    knowledgeLevel: 0,
    practicalStatus: "advanced",
    workAuthorization: "independent",
    supervisorId: "user_mgr_central",
  },
  {
    id: "ep_amir",
    userId: "user_emp_amir",
    organizationId: ORG_ID,
    branchId: BRANCH_SECOND,
    jobRole: "gold_purchasing",
    hireDate: "2024-07-18",
    knowledgeLevel: 0,
    practicalStatus: "training_required",
    workAuthorization: "none",
    supervisorId: "user_mgr_second",
    notes: "در حال گذراندن دوره شناخت طلا و محاسبات قیمت",
  },
  {
    id: "ep_leila",
    userId: "user_emp_leila",
    organizationId: ORG_ID,
    branchId: BRANCH_CENTRAL,
    jobRole: "sales_associate",
    hireDate: "2025-01-08",
    knowledgeLevel: 0,
    practicalStatus: "not_evaluated",
    workAuthorization: "none",
    supervisorId: "user_mgr_central",
    learningPathId: "path_newhire",
    streakDays: 0,
    notes: "کارمند جدید — مسیر یادگیری تازه‌واردان",
  },
];

export const courses: Course[] = [
  {
    id: "course_01",
    organizationId: ORG_ID,
    title: "استاندارد ورود به گالری لوکس",
    academy: "آکادمی آریا · US · CH · EU",
    version: 3,
    description:
      "دامنه ARYA-ONB: Floor Walk و Dual Control (الگوی JA / آمریکا) + Dress & Demeanor سطح quiet luxury سوئیسی — قبل از هر تماس با ویترین.",
    category: "آشنایی",
    estimatedMinutes: 90,
    difficulty: "beginner",
    targetJobRoles: [
      "sales_associate",
      "cashier",
      "customer_service",
      "repair_intake",
      "inventory",
      "gold_purchasing",
      "back_office",
      "accountant",
      "store_manager",
    ],
    coverAccent: "#8B6914",
    thumbnailColor: "#8B6914",
    coverImage: "/illustrations/topic-onboarding.png",
    isPublished: true,
    sortOrder: 1,
    requiredForAuthorization: true,
  },
  {
    id: "course_02",
    organizationId: ORG_ID,
    title: "سواد محصول جواهر و طلا",
    academy: "آکادمی آریا · GIA · CIBJO · Swiss Mark",
    version: 3,
    description:
      "دامنه ARYA-PRD: سواد محصول به سبک GIA، نام‌گذاری CIBJO Precious Metals، دقت نشانه‌گذاری سوئیسی، و افشاگری صادقانه الگوی FTC — بدون ادعای غیرمستند.",
    category: "محصول",
    estimatedMinutes: 120,
    difficulty: "beginner",
    targetJobRoles: [
      "sales_associate",
      "gold_purchasing",
      "inventory",
      "repair_intake",
      "store_manager",
    ],
    coverAccent: "#A67C00",
    thumbnailColor: "#A67C00",
    coverImage: "/illustrations/topic-product.png",
    isPublished: true,
    sortOrder: 2,
    requiredForAuthorization: true,
  },
  {
    id: "course_03",
    organizationId: ORG_ID,
    title: "شفافیت قیمت و محاسبه حرفه‌ای",
    academy: "آکادمی آریا · EU Transparency · FTC",
    version: 3,
    description:
      "دامنه ARYA-PRC: شفافیت قیمت مصرف‌کننده اروپا + افشاگری صادقانه آمریکایی — فلز، اجرت، سود، مالیات؛ رقم دقیق، توضیح آرام؛ دروازه مجوز کار پس از ارزیابی عملی.",
    category: "محاسبات",
    estimatedMinutes: 150,
    difficulty: "intermediate",
    targetJobRoles: [
      "sales_associate",
      "cashier",
      "accountant",
      "gold_purchasing",
      "store_manager",
    ],
    coverAccent: "#B8860B",
    thumbnailColor: "#B8860B",
    coverImage: "/illustrations/topic-pricing.png",
    isPublished: true,
    sortOrder: 3,
    requiredForAuthorization: true,
  },
  {
    id: "course_04",
    organizationId: ORG_ID,
    title: "فروش مشورتی (Consultative Selling)",
    academy: "آکادمی آریا · JA · Quiet Luxury",
    version: 3,
    description:
      "دامنه ARYA-SAL: Consultative Selling به سبک Jewelers of America و مهمان‌نوازی آرام سوئیسی — حداکثر دو گزینه، بدون فشار.",
    category: "فروش",
    estimatedMinutes: 110,
    difficulty: "intermediate",
    targetJobRoles: ["sales_associate", "store_manager", "customer_service"],
    coverAccent: "#6B4423",
    thumbnailColor: "#6B4423",
    coverImage: "/illustrations/topic-sales.png",
    isPublished: true,
    sortOrder: 4,
    requiredForAuthorization: false,
  },
  {
    id: "course_05",
    organizationId: ORG_ID,
    title: "تجربه مشتری و مهمان‌نوازی گالری",
    academy: "آکادمی آریا · CH Quiet Luxury · EU",
    version: 3,
    description:
      "مهمان‌نوازی آرام سوئیسی و احترام به حریم خصوصی اروپایی: خوشامد، خرید هدیه خصوصی، مدیریت نارضایتی بدون نمایش عمومی.",
    category: "ارتباطات",
    estimatedMinutes: 100,
    difficulty: "beginner",
    targetJobRoles: [
      "sales_associate",
      "cashier",
      "customer_service",
      "repair_intake",
    ],
    coverAccent: "#5C4033",
    thumbnailColor: "#5C4033",
    coverImage: "/illustrations/topic-care.png",
    isPublished: true,
    sortOrder: 5,
    requiredForAuthorization: false,
  },
  {
    id: "course_06",
    organizationId: ORG_ID,
    title: "امنیت عملیاتی شعبه",
    academy: "آکادمی آریا · Dual Control US · EU",
    version: 3,
    description:
      "دامنه ARYA-SEC: کنترل دوگانه آمریکایی و انضباط گالری اروپایی — باز/بسته دو نفره، ویترین قفل‌دار، واکنش اضطراری؛ دروازه مجوز کار.",
    category: "امنیت",
    estimatedMinutes: 95,
    difficulty: "intermediate",
    targetJobRoles: [
      "sales_associate",
      "cashier",
      "inventory",
      "store_manager",
      "back_office",
    ],
    coverAccent: "#4A3728",
    thumbnailColor: "#4A3728",
    coverImage: "/illustrations/topic-security.png",
    isPublished: true,
    sortOrder: 6,
    requiredForAuthorization: true,
  },
  {
    id: "course_07",
    organizationId: ORG_ID,
    title: "امانت کالا و کنترل موجودی",
    academy: "آکادمی آریا · JA Custody",
    version: 3,
    description:
      "دامنه ARYA-OPS: زنجیره امانت به سبک رویه فروشگاهی آمریکا — کدگذاری، تحویل شیفت، شمارش دوره‌ای، مغایرت‌گیری.",
    category: "عملیات",
    estimatedMinutes: 105,
    difficulty: "intermediate",
    targetJobRoles: ["inventory", "store_manager", "sales_associate", "accountant"],
    coverAccent: "#7A5C2E",
    thumbnailColor: "#7A5C2E",
    coverImage: "/illustrations/topic-inventory.png",
    isPublished: true,
    sortOrder: 7,
    requiredForAuthorization: false,
  },
  {
    id: "course_08",
    organizationId: ORG_ID,
    title: "پذیرش تعمیرات و زنجیره ردیابی",
    academy: "آکادمی آریا · Swiss Service Trace",
    version: 3,
    description:
      "دامنه ARYA-SVC: اسناد خدمات سطح سوئیس — ثبت قطعه، تخمین شفاف، رسید رسمی، تحویل هویت‌سنجی‌شده.",
    category: "خدمات",
    estimatedMinutes: 80,
    difficulty: "beginner",
    targetJobRoles: ["repair_intake", "sales_associate", "customer_service"],
    coverAccent: "#8B7355",
    thumbnailColor: "#8B7355",
    coverImage: "/illustrations/topic-repair.png",
    isPublished: true,
    sortOrder: 8,
    requiredForAuthorization: false,
  },
  {
    id: "course_09",
    organizationId: ORG_ID,
    title: "Clienteling و باشگاه مشتریان",
    academy: "آکادمی آریا · EU Privacy · Clienteling",
    version: 3,
    description:
      "Clienteling با حریم خصوصی اروپایی: ثبت سلیقه/مناسبت محرمانه، یادآوری محترمانه، پیشنهاد غیرتهاجمی.",
    category: "CRM",
    estimatedMinutes: 85,
    difficulty: "beginner",
    targetJobRoles: [
      "sales_associate",
      "cashier",
      "customer_service",
      "store_manager",
    ],
    coverAccent: "#9C7A3C",
    thumbnailColor: "#9C7A3C",
    coverImage: "/illustrations/topic-crm.png",
    isPublished: true,
    sortOrder: 9,
    requiredForAuthorization: false,
  },
  {
    id: "course_10",
    organizationId: ORG_ID,
    title: "پیشگیری از تقلب و ریسک عملیاتی",
    academy: "آکادمی آریا · CIBJO · RJC · US LP",
    version: 3,
    description:
      "دامنه ARYA-INT: اخلاق CIBJO/RJC + پیشگیری تقلب فروشگاهی آمریکایی — گزارش سریع بدون توهین؛ دروازه مجوز کار.",
    category: "ریسک",
    estimatedMinutes: 100,
    difficulty: "advanced",
    targetJobRoles: [
      "sales_associate",
      "cashier",
      "store_manager",
      "gold_purchasing",
      "inventory",
    ],
    coverAccent: "#5D4037",
    thumbnailColor: "#5D4037",
    coverImage: "/illustrations/topic-fraud.png",
    isPublished: true,
    sortOrder: 10,
    requiredForAuthorization: true,
  },
];

export const courseModules: CourseModule[] = [
  {
    id: "mod_01_1",
    courseId: "course_01",
    title: "اولین روز در گالری",
    description: "معرفی فضا، همکاران، و انتظارات رفتاری",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_01_1_1", "les_01_1_2"],
  },
  {
    id: "mod_01_2",
    courseId: "course_01",
    title: "قوانین داخلی و ظاهر حرفه‌ای",
    description: "پوشش، حضور و غیاب، و استفاده از موبایل",
    sortOrder: 2,
    order: 2,
    lessonIds: ["les_01_2_1"],
  },
  {
    id: "mod_02_1",
    courseId: "course_02",
    title: "عیار و نشانه‌گذاری",
    description: "GIA / CIBJO / Swiss Mark — عیار، مهر، نو و دست‌دوم",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_02_1_1"],
  },
  {
    id: "mod_02_2",
    courseId: "course_02",
    title: "انواع مصنوعات",
    description: "زنجیر، انگشتر، دستبند، سرویس و شمش",
    sortOrder: 2,
    order: 2,
    lessonIds: ["les_02_2_1"],
  },
  {
    id: "mod_03_1",
    courseId: "course_03",
    title: "فرمول قیمت‌گذاری",
    description: "اجزای قیمت نهایی طلا",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_03_1_1"],
  },
  {
    id: "mod_03_2",
    courseId: "course_03",
    title: "تمرین محاسبه",
    description: "حل مسائل واقعی فروشگاه",
    sortOrder: 2,
    order: 2,
    lessonIds: ["les_03_2_1"],
  },
  {
    id: "mod_04_1",
    courseId: "course_04",
    title: "نیازسنجی و ارائه",
    description: "از سلام تا پیشنهاد محصول",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_04_1_1"],
  },
  {
    id: "mod_05_1",
    courseId: "course_05",
    title: "اعتمادسازی",
    description: "ارتباط مؤثر در خریدهای احساسی",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_05_1_1"],
  },
  {
    id: "mod_06_1",
    courseId: "course_06",
    title: "پروتکل امنیت روزانه",
    description: "باز و بسته کردن و کنترل ویترین",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_06_1_1"],
  },
  {
    id: "mod_07_1",
    courseId: "course_07",
    title: "شمارش و مغایرت",
    description: "فرآیند شمارش موجودی",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_07_1_1"],
  },
  {
    id: "mod_08_1",
    courseId: "course_08",
    title: "پذیرش و تحویل تعمیر",
    description: "از ثبت تا تحویل به مشتری",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_08_1_1"],
  },
  {
    id: "mod_09_1",
    courseId: "course_09",
    title: "ثبت و پیگیری مشتری",
    description: "باشگاه مشتریان آریا",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_09_1_1"],
  },
  {
    id: "mod_10_1",
    courseId: "course_10",
    title: "نشانه‌های تقلب",
    description: "سناریوهای واقعی و گزارش‌دهی",
    sortOrder: 1,
    order: 1,
    lessonIds: ["les_10_1_1"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "les_01_1_1",
    moduleId: "mod_01_1",
    courseId: "course_01",
    title: "تور فروشگاه و معرفی بخش‌ها",
    summary: "تور فروشگاه و معرفی بخش‌ها",
    estimatedMinutes: 20,
    sortOrder: 1,
    hasQuiz: false,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_01_1_2",
    moduleId: "mod_01_1",
    courseId: "course_01",
    title: "نقش هر همکار در شعبه",
    summary: "نقش هر همکار در شعبه",
    estimatedMinutes: 15,
    sortOrder: 2,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: ["qq_01_1"],
  },
  {
    id: "les_01_2_1",
    moduleId: "mod_01_2",
    courseId: "course_01",
    title: "پوشش و رفتار حرفه‌ای",
    summary: "پوشش و رفتار حرفه‌ای",
    estimatedMinutes: 20,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: ["qq_01_1"],
  },
  {
    id: "les_02_1_1",
    moduleId: "mod_02_1",
    courseId: "course_02",
    title: "عیار ۷۵۰ و ۹۹۹ به زبان ساده",
    summary: "عیار ۷۵۰ و ۹۹۹ به زبان ساده",
    estimatedMinutes: 25,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: ["qq_02_1"],
  },
  {
    id: "les_02_2_1",
    moduleId: "mod_02_2",
    courseId: "course_02",
    title: "تشخیص مصنوعات رایج ویترین",
    summary: "تشخیص مصنوعات رایج ویترین",
    estimatedMinutes: 30,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_03_1_1",
    moduleId: "mod_03_1",
    courseId: "course_03",
    title: "اجزای قیمت نهایی",
    summary: "اجزای قیمت نهایی",
    estimatedMinutes: 30,
    sortOrder: 1,
    hasQuiz: false,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_03_2_1",
    moduleId: "mod_03_2",
    courseId: "course_03",
    title: "محاسبه قیمت یک انگشتر ۵ گرمی",
    summary: "محاسبه قیمت یک انگشتر ۵ گرمی",
    estimatedMinutes: 35,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: ["qq_03_1", "qq_03_2"],
  },
  {
    id: "les_04_1_1",
    moduleId: "mod_04_1",
    courseId: "course_04",
    title: "پنج گام فروش بدون فشار",
    summary: "پنج گام فروش بدون فشار",
    estimatedMinutes: 40,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: ["qq_04_1"],
  },
  {
    id: "les_05_1_1",
    moduleId: "mod_05_1",
    courseId: "course_05",
    title: "گوش دادن فعال پشت ویترین",
    summary: "گوش دادن فعال پشت ویترین",
    estimatedMinutes: 30,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_06_1_1",
    moduleId: "mod_06_1",
    courseId: "course_06",
    title: "باز و بسته کردن امن فروشگاه",
    summary: "باز و بسته کردن امن فروشگاه",
    estimatedMinutes: 35,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_07_1_1",
    moduleId: "mod_07_1",
    courseId: "course_07",
    title: "شمارش موجودی ویترین",
    summary: "شمارش موجودی ویترین",
    estimatedMinutes: 30,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_08_1_1",
    moduleId: "mod_08_1",
    courseId: "course_08",
    title: "فرم پذیرش تعمیر و رسید مشتری",
    summary: "فرم پذیرش تعمیر و رسید مشتری",
    estimatedMinutes: 25,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_09_1_1",
    moduleId: "mod_09_1",
    courseId: "course_09",
    title: "ثبت مشتری در باشگاه آریا",
    summary: "ثبت مشتری در باشگاه آریا",
    estimatedMinutes: 25,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: [],
  },
  {
    id: "les_10_1_1",
    moduleId: "mod_10_1",
    courseId: "course_10",
    title: "شناسایی رفتار مشکوک خریدار",
    summary: "شناسایی رفتار مشکوک خریدار",
    estimatedMinutes: 35,
    sortOrder: 1,
    hasQuiz: true,
    version: 1,
    quizQuestionIds: ["qq_10_1"],
  },
];

export const lessonContents: LessonContent[] = [
  {
    lessonId: "les_01_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "استاندارد ورود — US Dual Control · CH Quiet Luxury",
        body: "در گالری‌های معتبر آمریکا (الگوی Dual Control / JA) و بوتیک‌های سوئیسی، روز اول با Floor Walk امنیتی و عملیاتی آغاز می‌شود نه فروش. دامنه ARYA-ONB در آریا همین اصل را اجرا می‌کند: مناطق شعبه، مسیر اضطراری، قوانین لمس ویترین. شعبه مرکزی ولیعصر و شعبه بازار بزرگ هر دو با کنترل دوگانه گاوصندوق روز را شروع می‌کنند.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "نقشه ذهنی شعبه (مثل Floor Walk استاندارد)",
        body: "قبل از اولین تماس با مشتری این مسیر را حفظ کنید:",
        items: [
          "منطقه عمومی مشتریان (نشست و پذیرایی)",
          "ویترین‌های قفل‌دار طلای نو و سرویس",
          "میز مشاوره با سینی مخمل و نور نقطه‌ای",
          "میز ترازو و صندوق — بدون تجمع نامرتب",
          "اتاق پذیرش تعمیرات و ردیابی قطعه",
          "انبار موقت / گاوصندوق — دسترسی محدود",
        ],
      },
      {
        id: "b3",
        type: "example",
        title: "اصل جذب همکار در برندهای معتبر",
        body: "برندهای معتبر جواهر، کارمند را برای «نمایندگی اعتماد» استخدام می‌کنند: ظاهر مرتب، آرامش، دانش محصول، و انضباط امنیتی. فروش تهاجمی معیار استخدام نیست.",
      },
      {
        id: "b4",
        type: "warning",
        title: "قانون صفر ثانیه",
        body: "ویترین باز بدون قفل موقت — حتی چند ثانیه — تخلف جدی است و در ارزیابی عملی شما ثبت می‌شود.",
      },
    ],
  },
  {
    lessonId: "les_01_2_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "ظاهر و رفتار — Dress & Demeanor",
        body: "استاندارد بوتیک‌های لوکس: پوشش تیره/خنثی بدون جواهر اغراق‌آمیز شخصی، ناخن مرتب، عطر ملایم، و صدای آرام. مشتری باید احساس کند در فضای خصوصی و امن خرید می‌کند.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "چک‌لیست حضور حرفه‌ای",
        body: "",
        items: [
          "ورود با کارت/کد شخصی — بدون قرض دادن دسترسی",
          "تلفن شخصی در ساعت کار فقط برای موارد ضروری",
          "دست‌ها تمیز قبل از لمس کالا؛ استفاده از سینی نه کف دست",
          "مکالمه خصوصی مشتری شنیده نشود در جمع",
          "هرگز درباره بودجه مشتری با همکار دیگر شوخی نکنید",
        ],
      },
      {
        id: "b3",
        type: "warning",
        title: "خط قرمز",
        body: "عکس‌برداری از ویترین یا مشتری بدون مجوز مدیر ممنوع است.",
      },
    ],
  },
  {
    lessonId: "les_02_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "سواد عیار — GIA literacy · CIBJO · Swiss Mark",
        body: "دامنه ARYA-PRD: مشاور عیار را به زبان دقیق GIA/CIBJO توضیح می‌دهد و مهر را مثل دقت نشانه‌گذاری سوئیسی بررسی می‌کند. ۷۵۰ یعنی ۱۸ عیار (۷۵٪ طلا خالص)، ۹۹۹ نزدیک به طلای خالص. هرگز اصالت سنگ یا «سرمایه‌گذاری تضمینی» را بدون مدرک سازمان ادعا نکنید (افشاگری صادقانه الگوی FTC).",
      },
      {
        id: "b2",
        type: "checklist",
        title: "قبل از توضیح به مشتری",
        body: "",
        items: [
          "پلاک/مهر عیار را خودتان ببینید",
          "وزن را با ترازوی کالیبره اعلام کنید",
          "تفاوت نو و دست‌دوم را شفاف بگویید",
          "اگر مطمئن نیستید: «اجازه بدهید با مسئول محصول چک کنم»",
        ],
      },
      {
        id: "b3",
        type: "example",
        title: "جمله استاندارد",
        body: "«این قطعه ۱۸ عیار است؛ یعنی سه‌چهارم وزن آن طلای خالص است. اجرت ساخت جدا از ارزش فلز محاسبه می‌شود.»",
      },
    ],
  },
  {
    lessonId: "les_03_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "شفافیت قیمت — EU Transparency · FTC disclosure",
        body: "دامنه ARYA-PRC: در استاندارد اروپا شفافیت قیمت مصرف‌کننده الزامی است و الگوی FTC آمریکا ادعاهای مبهم را رد می‌کند. قیمت نهایی از چهار جزء ساخته می‌شود: ارزش طلا (وزن × عیار × نرخ روز)، اجرت ساخت، سود فروشگاه، و مالیات. مشتری حق دارد اجزا را بشنود — بدون شرم‌سار شدن از بودجه. نمره آزمون به‌تنهایی مجوز کار نمی‌دهد.",
      },
      {
        id: "b2",
        type: "formula",
        title: "فرمول عملیاتی آریا (ریال)",
        body: "نهایی = ارزش‌فلز + اجرت + سود + مالیات + ثابت\nارزش‌فلز = وزن × قیمت‌هرگرم‌عیار\nاجرت = ارزش‌فلز × درصداجرت\nسود = ارزش‌فلز × درصدرسود\nمالیات = (ارزش‌فلز + اجرت + سود) × درصدمالیات",
      },
      {
        id: "b3",
        type: "example",
        title: "مثال واقعی شعبه — ۵ گرم ۱۸ عیار",
        body: "فرض نرخ پایه ۱۸ عیار ۳۵٬۰۰۰٬۰۰۰ ریال/گرم، اجرت ۱۲٪، سود ۷٪، مالیات ۹٪، ثابت ۰.\nارزش فلز = ۵ × ۳۵٬۰۰۰٬۰۰۰ = ۱۷۵٬۰۰۰٬۰۰۰\nاجرت = ۱۷۵٬۰۰۰٬۰۰۰ × ۱۲٪ = ۲۱٬۰۰۰٬۰۰۰\nسود = ۱۷۵٬۰۰۰٬۰۰۰ × ۷٪ = ۱۲٬۲۵۰٬۰۰۰\nجمع = ۲۰۸٬۲۵۰٬۰۰۰\nمالیات = ۲۰۸٬۲۵۰٬۰۰۰ × ۹٪ = ۱۸٬۷۴۲٬۵۰۰\nنهایی ≈ ۲۲۶٬۹۹۲٬۵۰۰ ریال\nاین عدد را در کارگاه فرمول لمس کنید و با اسلایدر تغییر دهید.",
      },
      {
        id: "b4",
        type: "checklist",
        title: "قبل از اعلام رقم به مشتری",
        body: "",
        items: [
          "وزن را از ترازو بخوانید و بلند تکرار کنید",
          "عیار را از مهر/پلاک تأیید کنید",
          "نرخ روز را از تابلو یا سیستم شعبه بگیرید — نه حافظه",
          "اجرت همان مدل را از سیستم بکشید",
          "یک‌بار با همکار کنترل کنید",
          "اجزا را آرام برای مشتری بگویید",
        ],
      },
      {
        id: "b5",
        type: "warning",
        title: "اشتباه رایج",
        body: "مالیات را فقط روی ارزش طلای خام حساب نکنید مگر مدیر صراحتاً فرمول دیگری ابلاغ کند. گرد کردن بدون قاعده شعبه هم ممنوع است.",
      },
    ],
  },
  {
    lessonId: "les_03_2_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "تمرین محاسبه در سطح شعبه واقعی",
        body: "دقت رقم و لحن توضیح به اندازه خود عدد مهم است. در ارزیابی عملی، «محاسبه درست + توضیح آرام» معیار قبولی است؛ عجله یا پنهان‌کاری اجزا مردود است.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "پروتکل اعلام قیمت (Price Presentation)",
        body: "",
        items: [
          "وزن را از ترازو بخوانید و ثبت کنید",
          "عیار را از پلاک یا گواهی تأیید کنید",
          "اجرت همان مدل را از سیستم بگیرید",
          "نرخ روز را از تابلو/سیستم شعبه بگیرید",
          "رقم نهایی را یک‌بار با همکار کنترل کنید",
          "به مشتری با آرامش اجزا را خلاصه کنید",
        ],
      },
    ],
  },
  {
    lessonId: "les_04_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "فروش مشورتی — نه فشار",
        body: "در جواهرسازان معتبر آمریکا و اروپا، فروش «مشاوره‌ای» است: مناسبت، بودجه، و سلیقه اول است؛ سپس حداکثر دو گزینه مرتبط. فشار برای خرید همان روز خلاف استاندارد آریا و معیار رد صلاحیت عملی است.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "پنج گام Consultative Selling",
        body: "",
        items: [
          "خوش‌آمد کوتاه، فضای خصوصی، بدون ازدحام دور مشتری",
          "سؤال باز: مناسبت، بودجه تقریبی، ترجیح سبک",
          "نمایش روی سینی مخمل — حداکثر دو گزینه مرتبط",
          "پاسخ شفاف به نگرانی اجرت و قیمت",
          "پیشنهاد گام بعدی (رزرو، تعمیر سایز، مقایسه) بدون اجبار",
        ],
      },
      {
        id: "b3",
        type: "example",
        title: "جمله بستن محترمانه",
        body: "«اگر مایلید، می‌توانم این دو مدل را برای شما نگه دارم تا با همراهتان تصمیم بگیرید.»",
      },
    ],
  },
  {
    lessonId: "les_06_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "امنیت روزانه — Dual Control",
        body: "استاندارد فروشگاه‌های معتبر طلا: باز و بسته کردن فقط با حداقل دو نفر، ثبت ورود/خروج، و نگهداری کدها مطابق دفترچه امنیت. دوربین‌ها ابزار نظارت‌اند نه جایگزین انضباط فردی.",
      },
      {
        id: "b2",
        type: "warning",
        title: "ممنوع",
        body: "اشتراک‌گذاری کد گاوصندوق در پیام‌رسان یا یادداشت روی میز ممنوع است.",
      },
    ],
  },
  {
    lessonId: "les_10_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "ریسک عملیاتی — بدون اتهام عجولانه",
        body: "در فروشگاه‌های معتبر طلا، کارمند اول «محافظ اعتماد» است نه کارآگاه. نشانه‌های ریسک (عجله برای خروج بدون فاکتور، جابه‌جایی مکرر بدون علاقه واقعی، پرداخت غیرعادی) را بشناسید و بی‌صدا به مدیر گزارش دهید — هرگز مشتری را در صحنه متهم نکنید.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "پروتکل گزارش (Escalation)",
        body: "",
        items: [
          "آرام بمانید؛ لحن محترمانه حفظ شود",
          "کالا را روی میز/سینی نگه دارید — نه در دست مشتری در مسیر خروجی",
          "مدیر را با سیگنال توافق‌شده صدا کنید",
          "مسیر دوربین را مسدود نکنید",
          "پس از رویداد، جزئیات را در گزارش روزانه بنویسید",
        ],
      },
      {
        id: "b3",
        type: "example",
        title: "اصل برندهای معتبر",
        body: "امنیت خوب دیده نمی‌شود؛ مشتری درستکار باید فقط «حرفه‌ای بودن» را حس کند.",
      },
    ],
  },
  {
    lessonId: "les_01_1_2",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "نقش‌ها در گالری — چه کسی چه می‌کند",
        body: "فروشنده روی کف، صندوق روی تراکنش، انبار روی موجودی، پذیرش تعمیر روی سند قطعه، مدیر روی مجوز و کنترل دوگانه. مرز نقش‌ها را بدانید تا کار از دست نرود و امنیت نشکند.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "حداقل‌هایی که هر نیروی جدید باید بداند",
        body: "",
        items: [
          "چه کسی کلید ویترین را دارد و چه زمانی",
          "چه کسی فاکتور نهایی را تأیید می‌کند",
          "چه کسی کد گاوصندوق را می‌داند (حداقل دو نفر)",
          "مسیر اضطراری و نقطه تجمع",
          "چگونه به مدیر سیگنال ریسک بدهید",
        ],
      },
      {
        id: "b3",
        type: "warning",
        title: "مرز اختیار",
        body: "تخفیف خارج از سقف نقش، یا باز کردن ویترین بدون حضور دوم، تخلف عملیاتی است — حتی اگر «برای سرعت» باشد.",
      },
    ],
  },
  {
    lessonId: "les_02_2_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "انواع مصنوع و زبان ویترین",
        body: "زنجیر، دستبند، انگشتر، گوشواره، سرویس — هر دسته وزن، قفل، و نکته نگهداری خودش را دارد. مشتری باید بفهمد چه می‌خرد؛ نه اینکه فقط «طلا» بشنود.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "قبل از نمایش روی سینی",
        body: "",
        items: [
          "پلاک عیار و وزن را خودتان ببینید",
          "قفل و اتصالات را لمس و چک کنید",
          "خراش یا تغییر رنگ مشهود را گزارش دهید",
          "حداکثر دو گزینه مرتبط همزمان روی سینی",
          "سینی را بین خود و مشتری نگه دارید — نه پشت به دوربین",
        ],
      },
      {
        id: "b3",
        type: "example",
        title: "جمله استاندارد محصول",
        body: "«این زنجیر ۱۸ عیار است، وزن تقریبی… گرم، قفل جعبه‌ای دارد. اگر سایز گردن مشخص است، می‌توانم طول نزدیک را هم نشان دهم.»",
      },
    ],
  },
  {
    lessonId: "les_05_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "پذیرش تعمیر — سند قبل از قول",
        body: "الگوی خدمات سوئیسی: بدون رسید پذیرش، بدون عکس/شرح وضعیت، قطعه وارد کارگاه نمی‌شود. قول زمان تحویل باید از سیستم بیاید نه از حدس شما.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "چک‌لیست پذیرش",
        body: "",
        items: [
          "هویت مشتری و شماره تماس را ثبت کنید",
          "شرح آسیب و عکس وضعیت اولیه",
          "وزن و عیار اعلام‌شده را یادداشت کنید",
          "برآورد هزینه و زمان را شفاف بگویید",
          "رسید را به مشتری بدهید و نسخه شعبه را بایگانی کنید",
        ],
      },
      {
        id: "b3",
        type: "warning",
        title: "تحویل",
        body: "تحویل فقط با رسید و احراز هویت. قطعه را به «دوست مشتری» بدون مجوز کتبی ندهید.",
      },
    ],
  },
  {
    lessonId: "les_07_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "موجودی و امانت کالا",
        body: "هر خروج از ویترین باید در سیستم یا دفترچه ثبت شود. امانت گرفتن قطعه برای «نشان دادن به خانواده» بدون ثبت = ریسک سرقت و تخلف انضباطی.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "انضباط موجودی روزانه",
        body: "",
        items: [
          "شمارش نمونه ویترین در باز و بسته",
          "ثبت جابه‌جایی بین ویترین و انبار",
          "مغایرت را همان روز به مدیر گزارش دهید",
          "کالای امانی مشتری جدا از موجودی فروش علامت بخورد",
        ],
      },
    ],
  },
  {
    lessonId: "les_08_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "صندوق و تراکنش",
        body: "فاکتور باید با وزن، عیار، اجرت و مالیات هم‌خوان باشد. اصلاح دستی بدون اثر ممیزی ممنوع است. کارت، نقد، و کارت‌به‌کارت هر کدام پروتکل تأیید خود را دارند.",
      },
      {
        id: "b2",
        type: "checklist",
        title: "قبل از بستن فروش",
        body: "",
        items: [
          "رقم نهایی با فرمول شعبه یکی است",
          "مشتری اجزا را شنیده و تأیید کرده",
          "روش پرداخت ثبت شده",
          "نسخه فاکتور به مشتری داده شده",
        ],
      },
      {
        id: "b3",
        type: "warning",
        title: "نقدی بزرگ",
        body: "مبالغ نقدی بالاتر از سقف شعبه را طبق دستورالعمل مدیر و قوانین ضدپولشویی گزارش دهید — سکوت جایز نیست.",
      },
    ],
  },
  {
    lessonId: "les_09_1_1",
    blocks: [
      {
        id: "b1",
        type: "text",
        title: "ارتباط با مشتری و شکایت",
        body: "شکایت را شخصی نگیرید. گوش دهید، خلاصه کنید، راه‌حل در اختیار نقش خود پیشنهاد دهید، و اگر خارج از اختیار است به مدیر ارجاع دهید — با زمان پاسخ مشخص.",
      },
      {
        id: "b2",
        type: "example",
        title: "جمله استاندارد",
        body: "«متوجه نگرانی‌تان شدم. اجازه بدهید وضعیت فاکتور/تعمیر را در سیستم ببینم و تا … دقیقه به شما برگردم.»",
      },
      {
        id: "b3",
        type: "checklist",
        title: "پس از شکایت",
        body: "",
        items: [
          "ثبت در گزارش روزانه",
          "پیگیری تا بسته شدن پرونده",
          "بدون بحث علنی جلوی مشتریان دیگر",
        ],
      },
    ],
  },
];

export const learningPaths: LearningPath[] = [
  {
    id: "path_newhire",
    organizationId: ORG_ID,
    title: "بسته شایستگی نقش فروش",
    description:
      "اطلس دامنه‌ای US/CH/EU برای نقش فروش: ورود (ONB)، محصول (PRD)، قیمت (PRC)، فروش مشورتی (SAL)، امنیت (SEC). دانش ≠ مجوز کار.",
    targetJobRoles: ["sales_associate"],
    estimatedDays: 21,
    courseIds: ["course_01", "course_02", "course_03", "course_04", "course_06"],
  },
  {
    id: "path_cashier",
    organizationId: ORG_ID,
    title: "بسته شایستگی صندوق و حسابداری",
    description:
      "دوره عمیق شفافیت قیمت (PRC) و صداقت عملیاتی (INT) — تا متقاضی بداند مسیر حسابدار/صندوق مال اوست.",
    targetJobRoles: ["cashier", "accountant"],
    estimatedDays: 14,
    courseIds: ["course_03", "course_10"],
  },
  {
    id: "path_designer",
    organizationId: ORG_ID,
    title: "بسته عمیق طراح قطعه",
    description:
      "چشم بصری + سواد محصول + کارگاه ۳D — تئوری، استدلال فرمی، طراحی لمسی و آزمون؛ خروجی: «من طراح گالری‌ام».",
    targetJobRoles: ["designer"],
    estimatedDays: 28,
    courseIds: ["course_02", "course_01", "course_04"],
  },
  {
    id: "path_ideator",
    organizationId: ORG_ID,
    title: "بسته عمیق ایده‌پرداز فروشگاه",
    description:
      "ایده‌پردازی هر محصول، ست‌سازی، روایت فروش — تئوری ویترین + عملی ایده + سناریو؛ خروجی: «من ایده‌پرداز کف‌ام».",
    targetJobRoles: ["ideator"],
    estimatedDays: 21,
    courseIds: ["course_02", "course_04", "course_05"],
  },
];

export const learningPathCourses: LearningPathCourse[] = [
  {
    id: "lpc_1",
    learningPathId: "path_newhire",
    courseId: "course_01",
    sortOrder: 1,
    isRequired: true,
  },
  {
    id: "lpc_2",
    learningPathId: "path_newhire",
    courseId: "course_02",
    sortOrder: 2,
    isRequired: true,
  },
  {
    id: "lpc_3",
    learningPathId: "path_newhire",
    courseId: "course_03",
    sortOrder: 3,
    isRequired: true,
  },
  {
    id: "lpc_4",
    learningPathId: "path_newhire",
    courseId: "course_04",
    sortOrder: 4,
    isRequired: true,
  },
  {
    id: "lpc_5",
    learningPathId: "path_newhire",
    courseId: "course_06",
    sortOrder: 5,
    isRequired: true,
  },
  {
    id: "lpc_6",
    learningPathId: "path_cashier",
    courseId: "course_03",
    sortOrder: 1,
    isRequired: true,
  },
  {
    id: "lpc_7",
    learningPathId: "path_cashier",
    courseId: "course_10",
    sortOrder: 2,
    isRequired: true,
  },
  {
    id: "lpc_d1",
    learningPathId: "path_designer",
    courseId: "course_02",
    sortOrder: 1,
    isRequired: true,
  },
  {
    id: "lpc_d2",
    learningPathId: "path_designer",
    courseId: "course_01",
    sortOrder: 2,
    isRequired: true,
  },
  {
    id: "lpc_d3",
    learningPathId: "path_designer",
    courseId: "course_04",
    sortOrder: 3,
    isRequired: true,
  },
  {
    id: "lpc_i1",
    learningPathId: "path_ideator",
    courseId: "course_02",
    sortOrder: 1,
    isRequired: true,
  },
  {
    id: "lpc_i2",
    learningPathId: "path_ideator",
    courseId: "course_04",
    sortOrder: 2,
    isRequired: true,
  },
  {
    id: "lpc_i3",
    learningPathId: "path_ideator",
    courseId: "course_05",
    sortOrder: 3,
    isRequired: true,
  },
];

export const employeeAssignments: EmployeeAssignment[] = [
  {
    id: "asg_leila_path",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_leila",
    learningPathId: "path_newhire",
    assignedByUserId: "user_mgr_central",
    assignedAt: "2025-01-08T10:00:00.000Z",
    dueDate: "2025-01-29",
    status: "in_progress",
    priority: "high",
    isMandatory: true,
  },
  {
    id: "asg_amir_calc",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_amir",
    courseId: "course_03",
    assignedByUserId: "user_mgr_second",
    assignedAt: "2025-09-01T10:00:00.000Z",
    dueDate: "2025-09-25",
    status: "in_progress",
    priority: "high",
    isMandatory: true,
  },
  {
    id: "asg_maryam_sales",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_maryam",
    courseId: "course_04",
    assignedByUserId: "user_mgr_second",
    assignedAt: "2025-09-10T10:00:00.000Z",
    dueDate: "2025-09-30",
    status: "assigned",
    priority: "medium",
    isMandatory: true,
  },
  {
    id: "asg_nima_fraud",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_nima",
    courseId: "course_10",
    assignedByUserId: "user_trainer",
    assignedAt: WEEK_AGO,
    dueDate: "2025-09-27",
    status: "in_progress",
    priority: "medium",
    isMandatory: true,
  },
];

export const lessonProgress: LessonProgress[] = [
  {
    id: "lp_nima_01",
    organizationId: ORG_ID,
    userId: "user_emp_nima",
    lessonId: "les_01_1_1",
    courseId: "course_01",
    status: "completed",
    startedAt: "2024-01-16T09:00:00.000Z",
    completedAt: "2024-01-16T09:25:00.000Z",
    timeSpentSeconds: 1500,
    updatedAt: "2024-01-16T09:25:00.000Z",
    percent: 100,
  },
  {
    id: "lp_nima_03",
    organizationId: ORG_ID,
    userId: "user_emp_nima",
    lessonId: "les_03_2_1",
    courseId: "course_03",
    status: "completed",
    startedAt: "2024-02-01T10:00:00.000Z",
    completedAt: "2024-02-01T10:40:00.000Z",
    timeSpentSeconds: 2400,
    updatedAt: "2024-02-01T10:40:00.000Z",
    percent: 100,
  },
  {
    id: "lp_leila_01",
    organizationId: ORG_ID,
    userId: "user_emp_leila",
    lessonId: "les_01_1_1",
    courseId: "course_01",
    status: "completed",
    startedAt: "2025-01-09T09:00:00.000Z",
    completedAt: "2025-01-09T09:22:00.000Z",
    timeSpentSeconds: 1320,
    updatedAt: "2025-01-09T09:22:00.000Z",
    percent: 100,
  },
  {
    id: "lp_leila_02",
    organizationId: ORG_ID,
    userId: "user_emp_leila",
    lessonId: "les_01_1_2",
    courseId: "course_01",
    status: "in_progress",
    startedAt: "2025-09-18T11:00:00.000Z",
    timeSpentSeconds: 600,
    updatedAt: "2025-09-18T11:00:00.000Z",
    percent: 40,
  },
  {
    id: "lp_amir_03",
    organizationId: ORG_ID,
    userId: "user_emp_amir",
    lessonId: "les_03_1_1",
    courseId: "course_03",
    status: "completed",
    startedAt: "2025-09-05T14:00:00.000Z",
    completedAt: "2025-09-05T14:35:00.000Z",
    timeSpentSeconds: 2100,
    updatedAt: "2025-09-05T14:35:00.000Z",
    percent: 100,
  },
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: "qq_03_1",
    lessonId: "les_03_2_1",
    courseId: "course_03",
    prompt:
      "انگشتر ۵ گرمی ۱۸ عیار. قیمت هر گرم ۱۸ عیار ۳۵٬۰۰۰٬۰۰۰ ریال، اجرت ۱۲٪، سود ۷٪، مالیات ۹٪، هزینه ثابت ۰. قیمت نهایی چند ریال است؟ (گرد به نزدیک‌ترین عدد صحیح)",
    explanation:
      "ارزش طلا = ۵ × ۳۵٬۰۰۰٬۰۰۰ = ۱۷۵٬۰۰۰٬۰۰۰. با اجرت ۱۲٪ و سود ۷٪ و سپس مالیات ۹٪ محاسبه می‌شود.",
    type: "calculation",
    points: 10,
    difficulty: "hard",
    calculationAnswer: 226_992_500,
    calculationTolerance: 5000,
    calculationUnit: "ریال",
    calculationPayload: {
      weightGrams: 5,
      karat: 18,
      pricePerGram: 35_000_000,
      makingChargePerGram: 4_200_000,
      profitPercent: 7,
    },
  },
  {
    id: "qq_03_2",
    lessonId: "les_03_2_1",
    courseId: "course_03",
    prompt: "کدام جزء معمولاً روی «ارزش طلا + اجرت + سود» محاسبه می‌شود؟",
    explanation: "مالیات بر ارزش افزوده روی جمع اجزای مشمول اعمال می‌شود.",
    type: "single",
    points: 5,
  },
  {
    id: "qq_03_3",
    courseId: "course_03",
    prompt:
      "زنجیر ۱۰ گرمی. قیمت گرم ۳۴٬۰۰۰٬۰۰۰ ریال، اجرت ۸٪، سود ۵٪، مالیات ۹٪، هزینه ثابت ۵۰۰٬۰۰۰. قیمت نهایی؟",
    explanation: "ابتدا ارزش طلا، سپس اجرت و سود، بعد مالیات و هزینه ثابت.",
    type: "calculation",
    points: 10,
    calculationAnswer: 419_278_000,
    calculationTolerance: 10000,
    calculationUnit: "ریال",
  },
  {
    id: "qq_02_1",
    lessonId: "les_02_1_1",
    courseId: "course_02",
    prompt: "عیار ۷۵۰ به چه معناست؟",
    explanation: "۷۵۰ یعنی ۷۵۰ قسمت از ۱۰۰۰ طلای خالص؛ معادل ۱۸ عیار.",
    type: "single",
    points: 5,
  },
  {
    id: "qq_04_1",
    lessonId: "les_04_1_1",
    courseId: "course_04",
    prompt: "در فروش مشورتی، حداکثر چند گزینه هم‌زمان پیشنهاد می‌کنید؟",
    explanation: "دو گزینه مرتبط از سردرگمی مشتری جلوگیری می‌کند.",
    type: "single",
    points: 5,
  },
  {
    id: "qq_10_1",
    lessonId: "les_10_1_1",
    courseId: "course_10",
    prompt: "اگر مشتری اصرار به بردن کالا بدون فاکتور رسمی کند، اقدام درست چیست؟",
    explanation: "تحویل بدون فاکتور ممنوع است؛ مدیر را مطلع کنید.",
    type: "single",
    points: 5,
  },
  {
    id: "qq_01_1",
    lessonId: "les_01_2_1",
    courseId: "course_01",
    prompt: "کدام رفتار در شیفت فروش مجاز نیست؟",
    explanation: "استفاده شخصی از موبایل پشت ویترین ممنوع است.",
    type: "single",
    points: 5,
  },
];

export const quizOptions: QuizOption[] = [
  {
    id: "qo_03_2_a",
    questionId: "qq_03_2",
    text: "مالیات بر ارزش افزوده",
    isCorrect: true,
    sortOrder: 1,
  },
  {
    id: "qo_03_2_b",
    questionId: "qq_03_2",
    text: "هزینه ارسال پستی",
    isCorrect: false,
    sortOrder: 2,
  },
  {
    id: "qo_03_2_c",
    questionId: "qq_03_2",
    text: "پاداش فروشنده",
    isCorrect: false,
    sortOrder: 3,
  },
  {
    id: "qo_02_1_a",
    questionId: "qq_02_1",
    text: "۷۵۰ قسمت از ۱۰۰۰ طلای خالص (۱۸ عیار)",
    isCorrect: true,
    sortOrder: 1,
  },
  {
    id: "qo_02_1_b",
    questionId: "qq_02_1",
    text: "وزن قطعه به میلی‌گرم",
    isCorrect: false,
    sortOrder: 2,
  },
  {
    id: "qo_02_1_c",
    questionId: "qq_02_1",
    text: "شماره سریال کارخانه",
    isCorrect: false,
    sortOrder: 3,
  },
  {
    id: "qo_04_1_a",
    questionId: "qq_04_1",
    text: "حداکثر دو گزینه مرتبط",
    isCorrect: true,
    sortOrder: 1,
  },
  {
    id: "qo_04_1_b",
    questionId: "qq_04_1",
    text: "حداقل ده مدل از ویترین",
    isCorrect: false,
    sortOrder: 2,
  },
  {
    id: "qo_04_1_c",
    questionId: "qq_04_1",
    text: "فقط گران‌ترین مدل",
    isCorrect: false,
    sortOrder: 3,
  },
  {
    id: "qo_10_1_a",
    questionId: "qq_10_1",
    text: "از تحویل بدون فاکتور خودداری و مدیر را مطلع کنید",
    isCorrect: true,
    sortOrder: 1,
  },
  {
    id: "qo_10_1_b",
    questionId: "qq_10_1",
    text: "برای حفظ فروش موافقت کنید",
    isCorrect: false,
    sortOrder: 2,
  },
  {
    id: "qo_10_1_c",
    questionId: "qq_10_1",
    text: "فقط شماره موبایل بگیرید و کالا را بدهید",
    isCorrect: false,
    sortOrder: 3,
  },
  {
    id: "qo_01_1_a",
    questionId: "qq_01_1",
    text: "استفاده شخصی طولانی از موبایل پشت ویترین",
    isCorrect: true,
    sortOrder: 1,
  },
  {
    id: "qo_01_1_b",
    questionId: "qq_01_1",
    text: "خوش‌آمدگویی به مشتری",
    isCorrect: false,
    sortOrder: 2,
  },
  {
    id: "qo_01_1_c",
    questionId: "qq_01_1",
    text: "ثبت سفارش در سیستم",
    isCorrect: false,
    sortOrder: 3,
  },
];

export const competencies: Competency[] = [
  {
    id: "comp_product",
    organizationId: ORG_ID,
    code: "ARYA-PRD",
    title: "سواد محصول و نشانه‌گذاری",
    description:
      "GIA + CIBJO Precious Metals + Swiss Mark: عیار، وزن، مهر، نو/دست‌دوم — بدون ادعای غیرمستند.",
    category: "محصول",
    relatedJobRoles: ["sales_associate", "gold_purchasing", "inventory", "designer", "ideator"],
    relatedCourseIds: ["course_02"],
  },
  {
    id: "comp_pricing",
    organizationId: ORG_ID,
    code: "ARYA-PRC",
    title: "شفافیت قیمت و محاسبه",
    description:
      "EU Transparency + FTC-style disclosure: تجزیه قیمت و محاسبه زنده؛ مجوز فقط پس از ارزیابی عملی.",
    category: "محاسبات",
    relatedJobRoles: ["sales_associate", "cashier", "accountant"],
    relatedCourseIds: ["course_03"],
  },
  {
    id: "comp_sales",
    organizationId: ORG_ID,
    code: "ARYA-SAL",
    title: "فروش مشورتی و مهمان‌نوازی",
    description:
      "JA consultative selling + Swiss quiet luxury: نیازسنجی، دو گزینه، بستن بدون فشار.",
    category: "فروش",
    relatedJobRoles: ["sales_associate", "store_manager", "ideator", "designer"],
    relatedCourseIds: ["course_04", "course_05"],
  },
  {
    id: "comp_security",
    organizationId: ORG_ID,
    code: "ARYA-SEC",
    title: "امنیت عملیاتی Dual Control",
    description:
      "کنترل دوگانه آمریکا و انضباط گالری اروپا: SOP باز/بسته، ویترین قفل‌دار.",
    category: "امنیت",
    relatedJobRoles: ["sales_associate", "cashier", "store_manager", "inventory"],
    relatedCourseIds: ["course_06", "course_01"],
  },
  {
    id: "comp_fraud",
    organizationId: ORG_ID,
    code: "ARYA-INT",
    title: "صداقت و ضدتقلب",
    description:
      "اخلاق CIBJO/RJC + loss prevention آمریکایی: تشخیص و گزارش بدون توهین.",
    category: "ریسک",
    relatedJobRoles: ["sales_associate", "cashier", "gold_purchasing"],
    relatedCourseIds: ["course_10"],
  },
  {
    id: "comp_repair",
    organizationId: ORG_ID,
    code: "ARYA-SVC",
    title: "خدمات و ردیابی تعمیر",
    description:
      "Swiss Service Trace: پذیرش اسنادی، تخمین شفاف، تحویل هویت‌سنجی‌شده.",
    category: "خدمات",
    relatedJobRoles: ["repair_intake", "customer_service"],
    relatedCourseIds: ["course_08"],
  },
];

export const employeeCompetencies: EmployeeCompetency[] = [
  {
    id: "ec_nima_product",
    organizationId: ORG_ID,
    userId: "user_emp_nima",
    competencyId: "comp_product",
    knowledgeLevel: 0,
    practicalStatus: "competent",
    workAuthorization: "independent",
    lastAssessedAt: "2025-06-15T10:00:00.000Z",
    assessedByUserId: "user_mgr_central",
  },
  {
    id: "ec_nima_pricing",
    organizationId: ORG_ID,
    userId: "user_emp_nima",
    competencyId: "comp_pricing",
    knowledgeLevel: 0,
    practicalStatus: "competent",
    workAuthorization: "independent",
    lastAssessedAt: "2025-06-15T10:00:00.000Z",
    assessedByUserId: "user_mgr_central",
  },
  {
    id: "ec_leila_product",
    organizationId: ORG_ID,
    userId: "user_emp_leila",
    competencyId: "comp_product",
    knowledgeLevel: 0,
    practicalStatus: "not_evaluated",
    workAuthorization: "none",
  },
  {
    id: "ec_leila_pricing",
    organizationId: ORG_ID,
    userId: "user_emp_leila",
    competencyId: "comp_pricing",
    knowledgeLevel: 0,
    practicalStatus: "not_evaluated",
    workAuthorization: "none",
  },
  {
    id: "ec_amir_pricing",
    organizationId: ORG_ID,
    userId: "user_emp_amir",
    competencyId: "comp_pricing",
    knowledgeLevel: 0,
    practicalStatus: "training_required",
    workAuthorization: "none",
    lastAssessedAt: "2025-08-20T10:00:00.000Z",
    assessedByUserId: "user_mgr_second",
  },
  {
    id: "ec_maryam_sales",
    organizationId: ORG_ID,
    userId: "user_emp_maryam",
    competencyId: "comp_sales",
    knowledgeLevel: 0,
    practicalStatus: "supervised",
    workAuthorization: "supervised_only",
    lastAssessedAt: "2025-07-10T10:00:00.000Z",
    assessedByUserId: "user_mgr_second",
  },
];

export const practicalAssessments: PracticalAssessment[] = [
  {
    id: "pa_nima_1",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_nima",
    competencyId: "comp_pricing",
    assessorUserId: "user_mgr_central",
    assessedAt: "2025-06-15T10:00:00.000Z",
    practicalStatus: "competent",
    workAuthorization: "independent",
    score: 92,
    notes:
      "محاسبه سه سناریوی زنده را بدون خطا انجام داد و توضیح مشتری‌پسند ارائه کرد.",
    evidenceChecklist: [
      "محاسبه روی ترازو و سیستم",
      "توضیح اجرت به مشتری آزمایشی",
      "کنترل فاکتور نهایی",
    ],
  },
  {
    id: "pa_maryam_1",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_maryam",
    competencyId: "comp_sales",
    assessorUserId: "user_mgr_second",
    assessedAt: "2025-07-10T10:00:00.000Z",
    practicalStatus: "supervised",
    workAuthorization: "supervised_only",
    score: 75,
    notes: "نیازسنجی خوب است؛ در بستن فروش هنوز به همراهی مدیر نیاز دارد.",
    evidenceChecklist: ["نقش‌آفرینی فروش", "مدیریت اعتراض قیمت"],
  },
  {
    id: "pa_amir_1",
    organizationId: ORG_ID,
    employeeUserId: "user_emp_amir",
    competencyId: "comp_pricing",
    assessorUserId: "user_mgr_second",
    assessedAt: "2025-08-20T10:00:00.000Z",
    practicalStatus: "training_required",
    workAuthorization: "none",
    score: 48,
    notes:
      "در محاسبه مالیات اشتباه کرد. مجوز کار مستقل یا تحت نظارت داده نمی‌شود تا دوره محاسبات کامل شود.",
    evidenceChecklist: ["آزمون عملی محاسبه", "توضیح شفاهی فرمول"],
  },
];

export const trainingScenarios: TrainingScenario[] = [
  {
    id: "sc_sales_budget",
    organizationId: ORG_ID,
    title: "فروش با بودجه محدود",
    description:
      "مشتری برای هدیه ازدواج بودجه مشخصی دارد و بین دو مدل مردد است.",
    intro: "مشتری با بودجه محدود برای هدیه نامزدی آمده است. نیازسنجی کنید.",
    type: "sales",
    category: "فروش",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    relatedCourseIds: ["course_04", "course_05"],
  },
  {
    id: "sc_fraud_switch",
    organizationId: ORG_ID,
    title: "سوءظن تعویض کالا",
    description:
      "مشتری چند قطعه را جابه‌جا می‌کند و رفتارش مشکوک به نظر می‌رسد.",
    intro: "رفتار مشکوک پشت ویترین — امنیت کالا را حفظ کنید.",
    type: "fraud",
    category: "ضدتقلب",
    difficulty: "advanced",
    estimatedMinutes: 15,
    relatedCourseIds: ["course_10", "course_06"],
  },
];

export const scenarioSteps: ScenarioStep[] = [
  {
    id: "ss_sales_1",
    scenarioId: "sc_sales_budget",
    sortOrder: 1,
    narratorText:
      "خانم احمدی وارد شعبه مرکزی می‌شود و می‌گوید برای هدیه نامزدی حدود ۲۰۰ میلیون تومان بودجه دارد.",
    prompt: "اولین اقدام شما چیست؟",
    choices: [
      {
        id: "sc_s1_a",
        text: "ابتدا مناسبت، سلیقه و محدودیت وزن را بپرسید",
        isCorrect: true,
        feedback:
          "عالی. نیازسنجی دقیق، پیشنهاد مرتبط می‌سازد و از نمایش مدل‌های نامربوط جلوگیری می‌کند.",
        nextStepId: "ss_sales_2",
        scoreDelta: 10,
      },
      {
        id: "sc_s1_b",
        text: "گران‌ترین سرویس ویترین را بیاورید",
        isCorrect: false,
        feedback:
          "نمایش مدل خارج از بودجه اعتماد را کم می‌کند. ابتدا بودجه و سلیقه را تأیید کنید.",
        nextStepId: "ss_sales_2",
        scoreDelta: -5,
      },
      {
        id: "sc_s1_c",
        text: "بگویید با این بودجه گزینه مناسبی نیست",
        isCorrect: false,
        feedback:
          "گزینه‌های مناسب در این بازه وجود دارد. مشتری را زود ناامید نکنید.",
        nextStepId: "ss_sales_2",
        scoreDelta: -8,
      },
    ],
  },
  {
    id: "ss_sales_2",
    scenarioId: "sc_sales_budget",
    sortOrder: 2,
    narratorText:
      "او حلقه ساده و یک جفت گوشواره ظریف می‌خواهد. دو مدل در بودجه او موجود است.",
    prompt: "چگونه ادامه می‌دهید؟",
    choices: [
      {
        id: "sc_s2_a",
        text: "دو گزینه را با تفاوت اجرت و ظاهر مقایسه کنید",
        isCorrect: true,
        feedback:
          "مقایسه شفاف کمک می‌کند مشتری با اطمینان تصمیم بگیرد.",
        scoreDelta: 10,
      },
      {
        id: "sc_s2_b",
        text: "فقط روی تخفیف غیرمجاز تأکید کنید",
        isCorrect: false,
        feedback:
          "تخفیف خارج از سیاست شعبه مجاز نیست. ارزش و تناسب را توضیح دهید.",
        scoreDelta: -10,
      },
    ],
  },
  {
    id: "ss_fraud_1",
    scenarioId: "sc_fraud_switch",
    sortOrder: 1,
    narratorText:
      "آقایی چند انگشتر را پشت سر هم روی میز جابه‌جا می‌کند و حواس شما را با سؤال‌های پیاپی پرت می‌کند.",
    prompt: "واکنش صحیح؟",
    choices: [
      {
        id: "sc_f1_a",
        text: "کالا را کنترل‌شده روی میز نگه دارید و مدیر را بی‌صدا خبر کنید",
        isCorrect: true,
        feedback:
          "درست است. امنیت کالا اولویت دارد و اتهام مستقیم بدون شواهد ممنوع است.",
        nextStepId: "ss_fraud_2",
        scoreDelta: 15,
      },
      {
        id: "sc_f1_b",
        text: "با صدای بلند او را به تقلب متهم کنید",
        isCorrect: false,
        feedback:
          "اتهامات علنی خطرناک و غیرحرفه‌ای است. پروتکل امنیتی را دنبال کنید.",
        nextStepId: "ss_fraud_2",
        scoreDelta: -15,
      },
      {
        id: "sc_f1_c",
        text: "ویترین را باز بگذارید و به صندوق بروید",
        isCorrect: false,
        feedback: "هرگز ویترین و کالا را بدون نظارت رها نکنید.",
        nextStepId: "ss_fraud_2",
        scoreDelta: -20,
      },
    ],
  },
  {
    id: "ss_fraud_2",
    scenarioId: "sc_fraud_switch",
    sortOrder: 2,
    narratorText:
      "مدیر می‌رسد. مشتری می‌گوید عجله دارد و می‌خواهد بدون فاکتور یکی را ببرد.",
    prompt: "اقدام نهایی؟",
    choices: [
      {
        id: "sc_f2_a",
        text: "تحویل بدون فاکتور را رد کنید و فرآیند رسمی را ادامه دهید",
        isCorrect: true,
        feedback:
          "صحیح. هیچ فروشی بدون فاکتور رسمی انجام نمی‌شود.",
        scoreDelta: 15,
      },
      {
        id: "sc_f2_b",
        text: "برای حفظ مشتری موافقت کنید",
        isCorrect: false,
        feedback: "تخلف جدی است و می‌تواند به زیان مالی و حقوقی منجر شود.",
        scoreDelta: -20,
      },
    ],
  },
];

export const sops: Sop[] = [
  {
    id: "sop_open",
    organizationId: ORG_ID,
    title: "باز کردن فروشگاه",
    category: "عملیات روزانه",
    currentVersionId: "sopv_open_2",
    requiredJobRoles: ["store_manager", "sales_associate", "cashier"],
    isActive: true,
    requiresAcknowledgment: true,
  },
  {
    id: "sop_close",
    organizationId: ORG_ID,
    title: "بستن فروشگاه",
    category: "عملیات روزانه",
    currentVersionId: "sopv_close_2",
    requiredJobRoles: ["store_manager", "sales_associate", "cashier"],
    isActive: true,
    requiresAcknowledgment: true,
  },
  {
    id: "sop_vitrine",
    organizationId: ORG_ID,
    title: "تحویل ویترین",
    category: "امنیت",
    currentVersionId: "sopv_vitrine_1",
    requiredJobRoles: ["sales_associate", "inventory", "store_manager"],
    isActive: true,
    requiresAcknowledgment: true,
  },
  {
    id: "sop_count",
    organizationId: ORG_ID,
    title: "شمارش موجودی",
    category: "موجودی",
    currentVersionId: "sopv_count_1",
    requiredJobRoles: ["inventory", "store_manager", "accountant"],
    isActive: true,
    requiresAcknowledgment: true,
  },
  {
    id: "sop_repair",
    organizationId: ORG_ID,
    title: "پذیرش قطعه برای تعمیر",
    category: "خدمات",
    currentVersionId: "sopv_repair_1",
    requiredJobRoles: ["repair_intake", "sales_associate"],
    isActive: true,
    requiresAcknowledgment: true,
  },
];

export const sopVersions: SopVersion[] = [
  {
    id: "sopv_open_2",
    sopId: "sop_open",
    version: 2,
    summary: "نسخه به‌روز با کنترل دو نفره گاوصندوق",
    steps: [
      "ورود دو نفره به فروشگاه و غیرفعال‌سازی دزدگیر",
      "بررسی سلامت دوربین‌ها و ثبت در دفتر امنیت",
      "باز کردن گاوصندوق با حضور همزمان مدیر شیفت و مسئول ویترین",
      "چیدمان ویترین طبق لیست صبحگاهی",
      "روشن کردن تابلو قیمت روز و کنترل ترازو",
      "آماده‌سازی صندوق و کارت‌خوان",
    ],
    warnings: [
      "باز کردن تک‌نفره گاوصندوق ممنوع است",
      "کد دزدگیر را در پیام‌رسان نفرستید",
    ],
    publishedAt: "2025-08-01T08:00:00.000Z",
    publishedByUserId: "user_owner",
  },
  {
    id: "sopv_close_2",
    sopId: "sop_close",
    version: 2,
    summary: "بستن پایان شیفت با شمارش سریع ویترین",
    steps: [
      "توقف پذیرش مشتری جدید ۱۵ دقیقه پیش از تعطیلی",
      "شمارش سریع اقلام ویترین و تطبیق با سیستم",
      "انتقال موجودی به گاوصندوق با دو امضا",
      "بستن صندوق و چاپ گزارش روزانه",
      "خاموشی ویترین و فعال‌سازی دزدگیر",
      "خروج دو نفره و قفل درها",
    ],
    warnings: [
      "مغایرت شمارش را همان شب به مدیر گزارش دهید",
      "کلیدها را در محل امن شعبه بگذارید",
    ],
    publishedAt: "2025-08-01T08:00:00.000Z",
    publishedByUserId: "user_owner",
  },
  {
    id: "sopv_vitrine_1",
    sopId: "sop_vitrine",
    version: 1,
    summary: "تحویل شیفت ویترین",
    steps: [
      "چاپ لیست اقلام ویترین از سیستم",
      "شمارش فیزیکی قطعه به قطعه با همکار تحویل‌گیرنده",
      "ثبت مغایرت در فرم تحویل",
      "امضای دو طرفه تحویل‌دهنده و تحویل‌گیرنده",
      "قفل موقت ویترین هنگام ترک میز",
    ],
    warnings: ["هرگز ویترین باز را بدون ناظر رها نکنید"],
    publishedAt: "2025-05-10T08:00:00.000Z",
    publishedByUserId: "user_mgr_central",
  },
  {
    id: "sopv_count_1",
    sopId: "sop_count",
    version: 1,
    summary: "شمارش دوره‌ای موجودی",
    steps: [
      "انتخاب بازه شمارش (روزانه ویترین / هفتگی انبار)",
      "توقف ورود و خروج کالا در زمان شمارش",
      "شمارش دو نفره و ثبت وزن و کد کالا",
      "مقایسه با موجودی سیستم",
      "ثبت مغایرت و ارجاع به مدیر",
    ],
    warnings: ["شمارش تک‌نفره اعتبار ندارد"],
    publishedAt: "2025-04-20T08:00:00.000Z",
    publishedByUserId: "user_mgr_central",
  },
  {
    id: "sopv_repair_1",
    sopId: "sop_repair",
    version: 1,
    summary: "پذیرش تعمیرات مشتریان",
    steps: [
      "ثبت مشخصات قطعه، وزن و عیب ظاهری",
      "عکس‌برداری از وضعیت اولیه",
      "صدور رسید با کد پیگیری برای مشتری",
      "قرار دادن قطعه در پاکت مهروموم‌شده",
      "ثبت تخمین زمان و هزینه تقریبی",
    ],
    warnings: [
      "بدون رسید، قطعه را تحویل نگیرید یا پس ندهید",
      "وعده زمان قطعی بدون هماهنگی تعمیرکار ندهید",
    ],
    publishedAt: "2025-03-01T08:00:00.000Z",
    publishedByUserId: "user_trainer",
  },
];

export const sopAcknowledgments: SopAcknowledgment[] = [
  {
    id: "sa_nima_open",
    organizationId: ORG_ID,
    sopId: "sop_open",
    sopVersionId: "sopv_open_2",
    versionId: "sopv_open_2",
    userId: "user_emp_nima",
    acknowledgedAt: "2025-08-05T09:00:00.000Z",
  },
  {
    id: "sa_nima_close",
    organizationId: ORG_ID,
    sopId: "sop_close",
    sopVersionId: "sopv_close_2",
    versionId: "sopv_close_2",
    userId: "user_emp_nima",
    acknowledgedAt: "2025-08-05T09:05:00.000Z",
  },
  {
    id: "sa_zahra_open",
    organizationId: ORG_ID,
    sopId: "sop_open",
    sopVersionId: "sopv_open_2",
    versionId: "sopv_open_2",
    userId: "user_emp_zahra",
    acknowledgedAt: "2025-08-06T09:00:00.000Z",
  },
  {
    id: "sa_leila_open",
    organizationId: ORG_ID,
    sopId: "sop_open",
    sopVersionId: "sopv_open_2",
    versionId: "sopv_open_2",
    userId: "user_emp_leila",
    acknowledgedAt: "2025-09-12T10:00:00.000Z",
  },
];

/** No seeded certificates — issued only on real exam pass with graded answers. */
export const certificates: Certificate[] = [];

export const trainingRecommendations: TrainingRecommendation[] = [
  {
    id: "rec_leila_02",
    organizationId: ORG_ID,
    userId: "user_emp_leila",
    courseId: "course_02",
    competencyId: "comp_product",
    reason: "نیروی تازه‌وارد",
    reasonCode: "new_hire",
    priority: "high",
    message:
      "به‌عنوان تازه‌وارد، دوره «شناخت طلا و مصنوعات» را قبل از ایستادن مستقل پشت ویترین کامل کنید.",
    estimatedMinutes: 120,
    createdAt: "2025-01-09T08:00:00.000Z",
    dismissed: false,
  },
  {
    id: "rec_amir_03",
    organizationId: ORG_ID,
    userId: "user_emp_amir",
    courseId: "course_03",
    competencyId: "comp_pricing",
    reason: "شکاف مهارتی",
    reasonCode: "skill_gap",
    priority: "high",
    message:
      "شکاف مهارتی در محاسبه قیمت شناسایی شد. تا تکمیل دوره و ارزیابی عملی، مجوز کار ندارید.",
    estimatedMinutes: 150,
    createdAt: "2025-08-21T08:00:00.000Z",
    dismissed: false,
  },
  {
    id: "rec_maryam_04",
    organizationId: ORG_ID,
    userId: "user_emp_maryam",
    courseId: "course_04",
    competencyId: "comp_sales",
    reason: "مجوز کار ناکافی",
    reasonCode: "low_authorization",
    priority: "medium",
    message:
      "مجوز شما فقط تحت نظارت است. تمرین سناریوی فروش و دوره اصول فروش را ادامه دهید.",
    estimatedMinutes: 110,
    scenarioId: "sc_sales_budget",
    createdAt: "2025-09-10T08:00:00.000Z",
    dismissed: false,
  },
];

export const notifications: Notification[] = [
  {
    id: "ntf_1",
    organizationId: ORG_ID,
    userId: "user_emp_leila",
    type: "assignment",
    title: "مسیر یادگیری جدید",
    body: "مسیر تازه‌وارد فروش برای شما فعال شد. مهلت: ۲۹ دی‌ماه مسیر آموزشی.",
    href: "/employee/courses",
    createdAt: "2025-01-08T10:05:00.000Z",
    read: false,
  },
  {
    id: "ntf_2",
    organizationId: ORG_ID,
    userId: "user_emp_amir",
    type: "assessment",
    title: "نتیجه ارزیابی عملی",
    body: "وضعیت عملی شما «نیاز به آموزش» ثبت شد. مجوز کار صادر نشد.",
    href: "/employee/skills",
    createdAt: "2025-08-20T11:00:00.000Z",
    read: false,
  },
  {
    id: "ntf_3",
    organizationId: ORG_ID,
    userId: "user_emp_nima",
    type: "sop",
    title: "نسخه جدید SOP باز کردن فروشگاه",
    body: "نسخه ۲ منتشر شد. لطفاً تأیید مطالعه را ثبت کنید.",
    href: "/employee/sop",
    createdAt: "2025-08-01T09:00:00.000Z",
    readAt: "2025-08-05T09:00:00.000Z",
    read: true,
  },
  {
    id: "ntf_4",
    organizationId: ORG_ID,
    userId: "user_mgr_central",
    type: "reminder",
    title: "ارزیابی عملی لیلا",
    body: "کارمند جدید آماده ارزیابی عملی شناخت محصول است.",
    href: "/manager/assessments",
    createdAt: WEEK_AGO,
    read: false,
  },
  {
    id: "ntf_5",
    organizationId: ORG_ID,
    userId: "user_emp_zahra",
    type: "certificate",
    title: "یادآوری تمدید دانش",
    body: "دوره مدیریت ریسک برای صندوق‌داران این ماه پیشنهاد شده است.",
    href: "/employee/courses",
    createdAt: "2025-09-15T08:00:00.000Z",
    read: false,
  },
];

export const pricingFormulaConfig: PricingFormulaConfig = {
  id: "price_cfg_1",
  organizationId: ORG_ID,
  name: "فرمول استاندارد گالری آریا",
  goldPricePerGram18k: 35_000_000,
  makingFeePercent: 12,
  profitPercent: 7,
  vatPercent: 9,
  fixedFee: 0,
  updatedAt: "2025-09-18T07:00:00.000Z",
  updatedByUserId: "user_owner",
};

export const dailyTraining: DailyTraining[] = [
  {
    id: "dt_2025_09_24",
    organizationId: ORG_ID,
    date: "2025-09-24",
    title: "تمرین امروز: توضیح اجرت به زبان ساده",
    tip: "اجرت را به‌عنوان هزینه ساخت و طراحی توضیح دهید، نه «پول اضافه». یک جمله کوتاه و شفاف کافی است.",
    microLessonTitle: "اجرت ساخت چیست؟",
    microLessonBody: "اجرت، هزینه طراحی و ساخت قطعه است و جدا از ارزش طلا محاسبه می‌شود. برای مشتری با یک جمله ساده توضیح دهید.",
    courseId: "course_03",
    questionId: "qq_03_2",
    focusCompetencyId: "comp_pricing",
  },
  {
    id: "dt_2025_09_23",
    organizationId: ORG_ID,
    date: "2025-09-23",
    title: "تمرین دیروز: نشانه‌های تعویض کالا",
    tip: "اگر مشتری چند قطعه را سریع جابه‌جا کرد، کالا را کنترل‌شده نگه دارید و مدیر را خبر کنید.",
    scenarioId: "sc_fraud_switch",
    courseId: "course_10",
    focusCompetencyId: "comp_fraud",
  },
  {
    id: "dt_2025_09_22",
    organizationId: ORG_ID,
    date: "2025-09-22",
    title: "تمرین: خوش‌آمدگویی ۳۰ ثانیه‌ای",
    tip: "نام برند را بگویید، لبخند بزنید، و یک سؤال باز درباره مناسبت بپرسید.",
    courseId: "course_04",
    scenarioId: "sc_sales_budget",
    focusCompetencyId: "comp_sales",
  },
];

/** No seeded exam attempts — scores only from graded answers. */
export const examAttempts: ExamAttempt[] = [];

export function createDemoState(): AppState {
  const state: AppState = {
    organization,
    branches,
    users,
    employeeProfiles,
    courses,
    courseModules,
    modules: courseModules,
    lessons,
    lessonContents,
    learningPaths,
    learningPathCourses,
    employeeAssignments,
    assignments: employeeAssignments,
    lessonProgress,
    quizQuestions,
    questions: quizQuestions,
    quizOptions,
    quizAttempts: [],
    examAttempts,
    competencies,
    employeeCompetencies,
    practicalAssessments,
    trainingScenarios,
    scenarios: trainingScenarios,
    scenarioSteps,
    scenarioAttempts: [],
    sops,
    sopVersions,
    sopAcknowledgments,
    certificates,
    trainingRecommendations,
    recommendations: trainingRecommendations,
    notifications,
    auditLogs: [
      {
        id: "audit_1",
        organizationId: ORG_ID,
        actorUserId: "user_mgr_central",
        action: "practical_assess",
        entityType: "practical_assessment",
        entityId: "pa_nima_1",
        summary: "ارزیابی عملی نیما صالحی — مجوز مستقل برای محاسبه قیمت",
        createdAt: "2025-06-15T10:05:00.000Z",
        metadata: {
          workAuthorization: "independent",
          knowledgeScoreIgnored: true,
        },
      },
      {
        id: "audit_2",
        organizationId: ORG_ID,
        actorUserId: "user_mgr_second",
        action: "authorization_change",
        entityType: "employee_profile",
        entityId: "ep_amir",
        summary: "مجوز کار امیر باقری به «بدون مجوز» تنظیم شد پس از ارزیابی عملی",
        createdAt: "2025-08-20T10:10:00.000Z",
        metadata: {
          workAuthorization: "none",
          fromExam: false,
        },
      },
    ],
    pricingFormulaConfig,
    dailyTraining,
    currentUserId: "user_emp_leila",
    theme: "light",
  };
  // Ensure knowledge/certs never ship fabricated
  for (const ep of state.employeeProfiles) {
    ep.knowledgeLevel = 0;
  }
  for (const ec of state.employeeCompetencies) {
    ec.knowledgeLevel = 0;
  }
  return state;
}
