// Credible references. `use` says what staff should actually learn from each one.
export const REFERENCES = [
  { id: 'gia-4c', group: 'سنگ‌شناسی', title: 'GIA 4Cs of Diamond Quality', org: 'Gemological Institute of America', url: 'https://4cs.gia.edu/', use: 'مرجع جهانی درجه‌بندی الماس: تراش، رنگ، شفافیت و قیراط؛ تصاویر مقایسه‌ای رایگان.' },
  { id: 'gia-enc', group: 'سنگ‌شناسی', title: 'GIA Gem Encyclopedia', org: 'Gemological Institute of America', url: 'https://www.gia.edu/gem-encyclopedia', use: 'برگه هر سنگ: سختی، فرآوری‌های رایج، مراقبت و شبیه‌سازها.' },
  { id: 'gia-report', group: 'سنگ‌شناسی', title: 'GIA Report Check', org: 'Gemological Institute of America', url: 'https://www.gia.edu/report-check-landing', use: 'استعلام آنلاین شماره گزارش گواهی GIA و تطبیق با سنگ.' },
  { id: 'cibjo', group: 'استاندارد', title: 'CIBJO Blue Books (Gold, Diamond, Gemstone, Pearl)', org: 'CIBJO — World Jewellery Confederation', url: 'https://www.cibjo.org/', use: 'واژه‌نامه و قواعد نام‌گذاری و افشای جهانی صنعت جواهر؛ مرجع «چه چیزی را چه بنامیم».' },
  { id: 'iso9202', group: 'استاندارد', title: 'ISO 9202 — Jewellery: Fineness of precious metal alloys', org: 'International Organization for Standardization', url: 'https://www.iso.org/', use: 'عیارهای استاندارد طلا، نقره، پلاتین و پالادیوم و قاعده «هیچ تلورانس منفی».' },
  { id: 'iso8653', group: 'استاندارد', title: 'ISO 8653 — Jewellery: Ring sizes', org: 'International Organization for Standardization', url: 'https://www.iso.org/', use: 'تعریف سایز انگشتر بر اساس محیط داخلی به میلی‌متر.' },
  { id: 'iso11426', group: 'استاندارد', title: 'ISO 11426 — Determination of gold: cupellation (fire assay)', org: 'International Organization for Standardization', url: 'https://www.iso.org/', use: 'روش مرجع و مخرب برای تعیین دقیق عیار طلا؛ چرا «ری‌گیری» مرجع نهایی است.' },
  { id: 'lbma', group: 'بازار', title: 'LBMA Good Delivery Rules', org: 'London Bullion Market Association', url: 'https://www.lbma.org.uk/', use: 'استاندارد جهانی شمش طلا و زنجیره تأمین مسئولانه.' },
  { id: 'wgc', group: 'بازار', title: 'World Gold Council — Gold research & education', org: 'World Gold Council', url: 'https://www.gold.org/', use: 'آمار تقاضای جهانی زیورآلات و آموزش پایه درباره طلا و بازار آن.' },
  { id: 'rjc', group: 'اخلاق و انطباق', title: 'RJC Code of Practices', org: 'Responsible Jewellery Council', url: 'https://www.responsiblejewellery.com/', use: 'کد رفتار مسئولانه: افشای محصول، زنجیره تأمین، حقوق کارکنان و ضدپولشویی.' },
  { id: 'ftc', group: 'اخلاق و انطباق', title: 'FTC Guides for the Jewelry Industry (16 CFR Part 23)', org: 'U.S. Federal Trade Commission', url: 'https://www.ecfr.gov/current/title-16/chapter-I/subchapter-B/part-23', use: 'نمونه روشن قواعد تبلیغ و افشا: آزمایشگاهی، شبیه‌ساز، فرآوری و عیار.' },
  { id: 'fatf', group: 'اخلاق و انطباق', title: 'FATF Guidance for Dealers in Precious Metals and Stones', org: 'Financial Action Task Force', url: 'https://www.fatf-gafi.org/', use: 'نشانه‌های هشدار پول‌شویی در معاملات طلا و جواهر.' },
  { id: 'jsa', group: 'امنیت', title: "Jewelers' Security Alliance — Crime prevention", org: "Jewelers' Security Alliance", url: 'https://jsa.org/', use: 'الگوهای واقعی سرقت از جواهرفروشی‌ها و رویه‌های پیشگیری.' },
  { id: 'reach', group: 'اخلاق و انطباق', title: 'EU REACH Annex XVII, entry 27 (Nickel)', org: 'European Chemicals Agency', url: 'https://echa.europa.eu/', use: 'محدودیت آزادسازی نیکل در زیورآلاتِ در تماس با پوست؛ پشتوانه توضیح حساسیت نیکل.' },
  { id: 'ir-vat', group: 'قوانین ایران', title: 'قانون مالیات بر ارزش افزوده — جزء ۲ بند ب ماده ۲۶ و قانون بودجه ۱۴۰۵', org: 'سازمان امور مالیاتی کشور', url: 'https://www.intamedia.ir/', use: 'اصل طلا، جواهر و پلاتین معاف است؛ مالیات فقط بر اجرت ساخت، سود فروشنده و حق‌العمل (نرخ ۱۴۰۵: ۱۰٪).' },
  { id: 'ir-moadian', group: 'قوانین ایران', title: 'سامانه مودیان و صورتحساب الکترونیکی', org: 'سازمان امور مالیاتی کشور', url: 'https://my.tax.gov.ir/', use: 'ثبت فاکتور فروش در سامانه مودیان و تفکیک اقلام مشمول و معاف.' },
  { id: 'ir-consumer', group: 'قوانین ایران', title: 'قانون حمایت از حقوق مصرف‌کنندگان (۱۳۸۸)', org: 'مجلس شورای اسلامی', url: 'https://rc.majlis.ir/', use: 'الزام عرضه‌کننده به ارائه اطلاعات صحیح کالا و فاکتور؛ پایه پاسخ‌گویی به شکایت.' },
  { id: 'ir-inso', group: 'قوانین ایران', title: 'سازمان ملی استاندارد ایران — عیارسنجی فلزات گران‌بها', org: 'INSO', url: 'https://inso.gov.ir/', use: 'استانداردهای ملی و آزمایشگاه‌های همکار عیارسنجی.' },
  { id: 'bk-untracht', group: 'کتاب', title: 'Jewelry Concepts and Technology — Oppi Untracht', org: 'کتاب مرجع ساخت جواهر', url: '', use: 'روش‌های ساخت، نگین‌گذاری و پرداخت؛ برای فهم «اجرت از کجا می‌آید».' },
  { id: 'bk-brepohl', group: 'کتاب', title: 'The Theory and Practice of Goldsmithing — Erhard Brepohl', org: 'کتاب مرجع زرگری', url: '', use: 'آلیاژها، چگالی، لحیم و رفتار فلز؛ پشتوانه فنی درس‌های عیار و تعمیر.' },
  { id: 'bk-read', group: 'کتاب', title: 'Gemmology — Peter G. Read', org: 'کتاب درسی سنگ‌شناسی', url: '', use: 'مبانی علمی سنگ‌ها، لوپ، شکست نور و تشخیص.' },
  { id: 'bk-spin', group: 'کتاب', title: 'SPIN Selling — Neil Rackham', org: 'کتاب فروش مشاوره‌ای', url: '', use: 'چارچوب پرسش‌های وضعیت، مشکل، پیامد و نیاز-منفعت.' },
  { id: 'bk-voss', group: 'کتاب', title: 'Never Split the Difference — Chris Voss', org: 'کتاب مذاکره', url: '', use: 'برچسب‌زدن احساس و آینه‌کردن برای مدیریت اعتراض بدون تقابل.' },
];

export const GLOSSARY = [
  { id: 'mazaneh', term: 'مظنه', def: 'قیمت یک مثقال طلای آب‌شده با عیار ۷۰۵؛ مبنای قیمت‌گذاری بازار ایران.' },
  { id: 'mesghal', term: 'مثقال', def: 'واحد وزن سنتی برابر ۴٫۶۰۸۳ گرم.' },
  { id: 'k43318', term: 'عدد ۴٫۳۳۱۸', def: 'ضریب تبدیل مظنه به قیمت گرم ۱۸ عیار: ۴٫۶۰۸۳ × ۷۰۵ ÷ ۷۵۰.' },
  { id: 'abshode', term: 'آب‌شده', def: 'طلای ذوب و ریخته‌شده به شکل قطعه که عیارش با آزمایش (ری‌گیری) مشخص می‌شود.' },
  { id: 'reygiri', term: 'ری‌گیری', def: 'عیارسنجی آزمایشگاهی طلا؛ نتیجه‌اش مبنای معامله آب‌شده است.' },
  { id: 'ayar', term: 'عیار', def: 'نسبت طلای خالص در آلیاژ؛ به هزارم (۷۵۰) یا قیراط (۱۸) بیان می‌شود.' },
  { id: 'karat-gold', term: 'قیراط (طلا)', def: 'بیان عیار از ۲۴؛ ۱۸ قیراط یعنی ۱۸ بخش طلا از ۲۴ بخش.' },
  { id: 'carat-gem', term: 'قیراط (سنگ)', def: 'واحد وزن سنگ قیمتی برابر ۰٫۲ گرم؛ ربطی به عیار طلا ندارد.' },
  { id: 'ojrat', term: 'اجرت ساخت', def: 'هزینه طراحی، ساخت و پرداخت قطعه؛ مشمول مالیات بر ارزش افزوده.' },
  { id: 'sood', term: 'سود فروشنده', def: 'سهم فروشگاه، معمولاً درصدی از مجموع ارزش طلا و اجرت؛ مشمول مالیات.' },
  { id: 'vat', term: 'مالیات بر ارزش افزوده طلا', def: 'در ۱۴۰۵، ۱۰٪ فقط از اجرت و سود و حق‌العمل؛ اصل طلا معاف است.' },
  { id: 'hobab', term: 'حباب سکه', def: 'اختلاف قیمت بازار سکه با ارزش طلای موجود در آن.' },
  { id: 'bahar', term: 'سکه بهار آزادی', def: 'سکه تمام ۸٫۱۳۳ گرم با عیار ۹۰۰؛ حدود ۷٫۳۲ گرم طلای خالص.' },
  { id: 'ang', term: 'انگ / مهر عیار', def: 'نشان عیار و سازنده روی قطعه؛ ادعای سازنده است نه تضمین.' },
  { id: 'gp', term: 'GP / GEP', def: 'آبکاری طلا (Gold Plated)؛ لایه بسیار نازک روی فلز دیگر.' },
  { id: 'gf', term: 'GF', def: 'روکش طلا (Gold Filled)؛ لایه ضخیم‌تر جوش‌خورده روی فلز پایه، اما طلای توپر نیست.' },
  { id: 'rhodium', term: 'آبکاری رودیوم', def: 'پوشش براق سفید روی طلای سفید؛ با زمان ساییده و قابل تجدید است.' },
  { id: 'electroform', term: 'الکتروفرمینگ', def: 'ساخت قطعه توخالی با رسوب الکتروشیمیایی طلا؛ حجم زیاد با وزن کم و حساس به ضربه.' },
  { id: 'lostwax', term: 'ریخته‌گری موم گم‌شده', def: 'ساخت با مدل مومی، قالب گچی و ریختن فلز مذاب؛ رایج‌ترین روش ساخت انگشتر.' },
  { id: 'lahim', term: 'لحیم', def: 'آلیاژ اتصال با نقطه ذوب پایین‌تر؛ لحیم زیاد می‌تواند عیار کل قطعه را پایین بیاورد.' },
  { id: 'brilliant', term: 'برلیان', def: 'نام یک تراش (Round Brilliant)، نه نوع سنگ؛ «الماس برلیان» یعنی الماس با این تراش.' },
  { id: 'table', term: 'تِیبل (سطح)', def: 'بزرگ‌ترین وجه تخت بالای سنگ تراش‌خورده.' },
  { id: 'girdle', term: 'کمربند (گردل)', def: 'لبه دور سنگ که تاج را از پاویون جدا می‌کند؛ محل لیزر شماره گواهی.' },
  { id: 'pavilion', term: 'پاویون', def: 'بخش پایینی سنگ که نور را به بالا بازمی‌گرداند.' },
  { id: 'culet', term: 'کولت', def: 'نوک یا وجه بسیار کوچک پایین پاویون.' },
  { id: 'mohs', term: 'مقیاس موس', def: 'مقیاس نسبی سختی (مقاومت در برابر خراش) از ۱ تا ۱۰.' },
  { id: 'labgrown', term: 'سنگ آزمایشگاهی', def: 'همان ترکیب و ساختار سنگ طبیعی، ساخت انسان؛ افشا الزامی است.' },
  { id: 'simulant', term: 'شبیه‌ساز', def: 'ماده‌ای متفاوت با ظاهر مشابه (مثل زیرکونیا برای الماس).' },
  { id: 'moissanite', term: 'موزونایت', def: 'سیلیکون کارباید؛ تستر حرارتی ساده ممکن است آن را الماس نشان دهد.' },
  { id: 'prong', term: 'نگین‌گذاری چنگی', def: 'نگه‌داشتن سنگ با چند پایه فلزی؛ نور بیشتر، نیازمند بازرسی دوره‌ای.' },
  { id: 'bezel', term: 'نگین‌گذاری کاسه‌ای', def: 'دیواره فلزی دور تا دور سنگ؛ امن‌ترین نوع برای استفاده روزمره.' },
  { id: 'pave', term: 'پاوه (دانه‌نشان)', def: 'سنگ‌های ریز کنار هم با دانه‌های فلزی کوچک؛ حساس به ضربه و اولتراسونیک.' },
  { id: 'loupe', term: 'لوپ ۱۰x', def: 'ذره‌بین استاندارد جواهر؛ درجه‌بندی شفافیت الماس بر اساس دید ۱۰ برابر است.' },
  { id: 'touchstone', term: 'سنگ محک', def: 'سنگ سیاه برای خط‌انداختن فلز و مقایسه واکنش با اسید یا سوزن مرجع.' },
  { id: 'xrf', term: 'XRF', def: 'دستگاه فلورسانس اشعه ایکس؛ ترکیب سطح را بدون آسیب نشان می‌دهد.' },
  { id: 'archimedes', term: 'آزمون ارشمیدس', def: 'محاسبه چگالی از وزن در هوا و در آب برای تخمین عیار.' },
  { id: 'cupellation', term: 'کوپلاسیون', def: 'آزمون آتش؛ دقیق‌ترین و مخرب‌ترین روش تعیین عیار طلا.' },
  { id: 'isosize', term: 'سایز ISO انگشتر', def: 'محیط داخلی انگشتر به میلی‌متر؛ سایز ۵۴ یعنی محیط ۵۴ میلی‌متر.' },
  { id: 'dual', term: 'کنترل دوگانه', def: 'انجام کارهای حساس (گاوصندوق، باز و بسته کردن) فقط با حضور دو نفر.' },
  { id: 'oneitem', term: 'قانون یک قطعه', def: 'در هر لحظه فقط یک قطعه بیرون از ویترین برای هر مشتری.' },
  { id: 'fab', term: 'FAB', def: 'ویژگی ← مزیت ← منفعت؛ تبدیل مشخصات قطعه به ارزش برای مشتری.' },
  { id: 'labeling', term: 'برچسب‌زدن احساس', def: 'نام‌بردن آرام از نگرانی مشتری («به نظر می‌رسد…») برای کاهش تنش.' },
  { id: 'moadian', term: 'سامانه مودیان', def: 'سامانه ثبت صورتحساب الکترونیکی سازمان امور مالیاتی.' },
  { id: 'chainrec', term: 'زنجیره ردیابی', def: 'ثبت هر جابه‌جایی قطعه امانی یا تعمیری با وزن، تاریخ و امضا.' },
];

export const PATH = ['c-metal', 'c-price', 'c-sales', 'c-security', 'c-product', 'c-gems', 'c-assay', 'c-service'];
